### ISSUE TITLE
vsce package fails with node version < 14

### ISSUE THREAD

**Issue by mikereiche** [couchbaselabs/VSCode-Couchbase#80]
**Describe the bug**
 % vsce package
/usr/local/lib/node_modules/vsce/out/package.js:136
    return (translations ?? [])
                          ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/vsce/out/main.js:27:19)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)

**Steps to reproduce**
If possible, provide a recipe for reproducing the error.

**What did you expect to see?**
A clear and concise description of what you expected to see.

**What did you see instead?**
A clear and concise description of what you saw instead.

**What version did you use?**
VSCode Version:
Extension Version:

**Additional context**
Fix - needs at least node version 14.

brew install node
brew link --overwrite node

Also - 'brew link node' on MacOs needs permissions changed before executing:
cd /usr/local && sudo chown -R $(whoami) bin etc include lib sbin share var Frameworks lib/dtrace

**Comment by mikereiche** [comment]
see https://github.com/microsoft/vscode-vsce/issues/653
